### ISSUE TITLE
What tools did you use for map?

### ISSUE THREAD

**Issue by titus-shoats** [jubalh/raymario#1]
Hi, awesome game, I was wondering what tools did you use to make your tilemap, and .bmp files for the game. I'm creating a basic side scroll game using raylib, and I'm drawing it out using arrays, and a text file for the map, which is a bit tedious.  Can you give me any advice on how did you create your map??? 

Thanks

**Comment by jubalh** [comment]
Here we are just using bmp files too.

My goal was to switch to [Tiled](http://www.mapeditor.org/) map editor, and then use [tmx](https://github.com/baylej/tmx) to parse the files.

I also created  an [issue](https://github.com/baylej/tmx/issues/31) about adding a raylib example to tmx. Also pinged @raysan5 about it. But so far it seems noone had time (me neither).

Good luck, @titus-shoats

**Comment by raysan5** [comment]
Hi @titus-shoats and @jubalh! Completely agree that creating the maps directly on a .txt file or even using pixel colors on a .bmp file is cumbersome.

Using a tile editor like [Tiled](http://www.mapeditor.org/) or [tIDE](http://tide.codeplex.com/) is desired but raylib can not import that data, a tmx importer should be used... but tmx fileformat is not simple, it has a lot of features and importing it to raylib requires some work.

Fortunately, right now I'm working on a [set of small tools](https://twitter.com/raysan5/status/950717577281658882) for gamedev, based on raylib. Planning to build a simple and easy-to-use tile editor very soon.

I'll keep you updated!

**Comment by jubalh** [comment]
@raysan5 sounds nice.

I think many people already are familiar with Tiled and use it in other projects.
Having in example on how to use the tmx C library (mentioned above) with raylib would in my opinion:
- help bring new people to raylib who already use something else (love2d for example) for prototyping , did their maps with tiled (most lua folks probabably) and now want to use C to get something nice
- help existing raylib users to easily create maps

Using Tiled would also distribute the workload. I understand you are doing many things, and maintaining a seperate tile map editor might be just too troublesome at times. Supporting an existing tool and sharing responsibilities sounds to me like the way to go.

[Here](https://github.com/baylej/tmx/blob/master/examples/sdl/sdl.c) is an example showing how people use tmx with sdl. They have another one for allegro. For someone who knows the internals of raylib, it should be fairly easy to modify that example to show how its done with raylib.

**Comment by titus-shoats** [comment]
Yea I think allegro has a few tutorials on how to use tiled/tmx with their platform. But either way, @raysan5  please keep me updated whenever your done with your tile editor for raylib. Thanks

**Comment by raysan5** [comment]
Hi @jubalh, please, don't misunderstood me, you're right, supporting Tiled tmx format is undoubtly the best option for most of the users that are already familiar with this amazing tool but tmx is a complex format with lot of features and also requires an additional external library.

My idea is creating a simple tool to just export a plain .txt or .bmp that can be directly imported and used by raylib with a couple of simple functions. Something way smaller than Tiled and simpler than [tmx format](https://github.com/baylej/tmx/wiki). Also for the fun of creating it.

**Comment by jubalh** [comment]
I understand. But I am not sure why you say that tmx is complicated, I mean I dont understand why that matters. I am not suggestring rewriting but using the existing tmx lib.
