### ISSUE TITLE
Collision Detection Question

### ISSUE THREAD

**Issue by titus-shoats** [jubalh/raymario#2]
Hey i've been working on my own version of your the ray mario, and im been trying to get my player to prevent colliding into the right and left boundaries of the floor/platforms (stair steps). My player is successfully walking on top of the platform/floor without collision, but i'm going through the platform/floor thats intended to be stairs/steps, or random platform/objects on the floor. Could you give my any advice, I have my code snippet below..

`

   Rectangle player = { 400,320,40,40 };
   Rectangle oldPlayer = player;
   Camera2D camera;
   Camera2D oldCamera = camera;

    while (!WindowShouldClose())    // Detect window close button or ESC key
	{
                oldPlayer = player;
		oldCamera = camera;

			if (IsKeyDown(KEY_RIGHT)) {
				player.x += 2;                  // Player movement
				camera.offset.x -= 2;       // Camera displacement with player movement
			}
			else if (IsKeyDown(KEY_LEFT)) {
				player.x -= 2;                    // Player movement
				camera.offset.x += 2;       // Camera displacement with player movement
			}

			// Collision
			for (int i = 0; i < MAX_FLOOR; i++) {

				if (CheckCollisionRecs(Rectangle{ player.x, player.y, player.width, player.height }, Rectangle{ (int)platforms[i].position.x, (int)platforms[i].position.y,(int)platforms[i].scale.x, (int)platforms[i].scale.y })) {
		
					// player and camera gets updated/starts fresh
					player = oldPlayer;
					camera = oldCamera;		
					
					if (IsKeyDown(KEY_RIGHT)) {
						player.x += 2;              // Player movement
						camera.offset.x -= 2;       // Camera displacement with player movement

					}
				}
				
			}
}
`

**Comment by jubalh** [comment]
@titus-shoats if you want to learn how to use a library please read the library code. please check the library website and its documentation.
i would like to help you with your current issue but have limited time.
